### ISSUE TITLE
DB writer unable to recover after Kafka outage

### ISSUE THREAD

**Issue by quarckster** [RedHatInsights/insights-results-aggregator#1032]
It's possible the situation when the db writer stops to consume messages from a Kafka topic. If Kafka had some outage db writer puts the following to the log:
```
ccx.ocp.results/0: dial tcp 10.130.20.14:9092: connect: connection refused
kafka: error while consuming ccx.ocp.results/0: EOF
Broker initialization error
```
Only the service restart can fix that. 

The db writer should be able to recover after Kafka outages.

**Comment by Sergey1011010** [comment]
The issue is in this function https://github.com/RedHatInsights/insights-results-aggregator/blob/master/aggregator.go#L214 we need to rewrite it so it stops the whole service after an error in either consumer or server part happened.
