### ISSUE TITLE
DELETE method for organizations endpoint

### ISSUE THREAD

**Issue by quarckster** [RedHatInsights/insights-results-aggregator#107]
There should be a way to delete an organization from the DB. It should accept multiple organization ids in order to perform the batch deletion.

**Comment by bond95** [comment]
Who can delete organisations from DB? Organisation administrator, or maybe someone from RH who has needed permissions?

**Comment by quarckster** [comment]
Anyone who can login to the cloud. I ask about this feature from the testing perspective. During the testing I will need to cleanup.

**Comment by tisnik** [comment]
Hmm should we expose this endpoint? Sounds a bit dangerous ;)

**Comment by quarckster** [comment]
@tisnik RHEL inventory service in cloud.redhat.com has DELETE https://github.com/RedHatInsights/insights-host-inventory/blob/master/swagger/api.spec.yaml#L130

**Comment by tisnik** [comment]
@quarckster they probably have some user story for it. We can implement DELETE, that is not a problem, just the 'state space' will be much bigger, it is a bit dangerous, and not required for user stories. OTOH we can create user story for testers. that's legit.

**Comment by quarckster** [comment]
@tisnik gotcha, perhaps we need to discuss it offline with PM

**Comment by Sergey1011010** [comment]
We can implement delete endpoints only in dev environment, it won't cause any security issues and will be useful for integration testing. 

@quarckster what should endpoint for batch deletion look like? Something like `/organizations/[0-9]{1,32}(,[0-9]{1,32})*`?

**Comment by tisnik** [comment]
@Sergey1011010 pls make sure to assign tasks in JIRA as I already started working on this task in parallel :/

**Comment by Sergey1011010** [comment]
@tisnik, no problems, you can assign yourself here, I have tasks for like/dislike endpoints which I will complete first :)
