### ISSUE TITLE
Remove SQLite support from project

### ISSUE THREAD

**Issue by bond95** [RedHatInsights/insights-results-aggregator#110]
SQLite we are using only for testing purposes, in production we will not use SQLite, but it bring some troubles with queries, which make code more complicated. So better solution is to remove SQLite from project at all.

**Comment by tisnik** [comment]
Beware that it makes testing more complicated and we'll be lock in one DB solution (with all idiosyncrasies that PostgreSQL has) which is not good in overall (especially for larger projects).

**Comment by bond95** [comment]
@tisnik we already had discussion with @quarckster about testing, and we agreed, that this is not so big problem.
About one DB solution, I should say that SQLite is not that DB that we gonna use in production, so maybe better to add support of other DB when we need it?

**Comment by tisnik** [comment]
@bond95 @quarckster what's the proposed solution then? use "real mocked DB" instead?

**Comment by bond95** [comment]
Use postgres in docker @quarckster am I right?

**Comment by quarckster** [comment]
Yes, I'm aware that it won't be unit tests anymore but I don't see a simple solution here.

**Comment by tisnik** [comment]
Just to be clear - about what tests are we talking about?

**Comment by quarckster** [comment]
The tests which will be run in Travis on every PR commit.

**Comment by tisnik** [comment]
I mean - IIRC there are just two incompatibilities between PostgreSQL and SQLite we found and probably not more. I'm a bit concerned about 1) having SQL-but-not-true-sql-just-postgressql-only lock  2) the sheer elegance of using memory-bases SQlite for unit tests

**Comment by quarckster** [comment]
If we keep sqlite it means we need to support two DBs and SQL dialects. I believe some abstractions around could help here. It could be some ORM like gorm.

**Comment by tisnik** [comment]
+1 @quarckster

**Comment by bond95** [comment]
I'm not sure using GORM is a good solution for 5 queries. I agree that it's better to use only one DB, but GORM is overhead for our solution especially if we use only postgres for production and have 5 queries.

**Comment by tisnik** [comment]
we might need more queries in the future, for example "like/dislike" functionality. Still not a complicated DB schema though..

(TBH personally I think that most ORMs are not usually necessary, but especially middleware people seems to dislike or not know SQL :) so they are forced to use it)

**Comment by tisnik** [comment]
@bond95 @quarckster what about using https://github.com/Masterminds/squirrel? It is not ORM, "just" quite nice abstraction over low level SQL commands.

**Comment by bond95** [comment]
@tisnik looks nice

**Comment by bond95** [comment]
Ok, so we agree on using `squirrel` so we can close that issue.
PS https://github.com/RedHatInsights/insights-results-aggregator/issues/111
