### ISSUE TITLE
Write unit tests with mocked kafka

### ISSUE THREAD

**Issue by Sergey1011010** [RedHatInsights/insights-results-aggregator#112]
This should mock kafka somehow https://github.com/Shopify/sarama/tree/master/mocks 

Those tests https://github.com/RedHatInsights/insights-results-aggregator/blob/master/tests/metrics/metrics_test.go could be rewritten using mocked kafka and of course we can test much more.

**Comment by tisnik** [comment]
Ack @Sergey1011010

**Comment by Sergey1011010** [comment]
should be closed with https://github.com/RedHatInsights/insights-results-aggregator/pull/99

**Comment by bond95** [comment]
@Sergey1011010 is this issue can be closed?

**Comment by Sergey1011010** [comment]
@bond95, yes
