### ISSUE TITLE
Remove configuration from main package

### ISSUE THREAD

**Issue by Bee-lee** [RedHatInsights/insights-results-aggregator#126]
Split configuration functions and related stuff to the according packages (server, storage, ...)

Having those configuration functions in package main means that for example the functions cant be called during testing of other packages (since you can't import main package, export tricks dont help here)

**Comment by Sergey1011010** [comment]
I see that you needed it for this pr https://github.com/RedHatInsights/insights-results-aggregator/pull/120 but it's been merged. Do we still want this refactoring?

**Comment by Bee-lee** [comment]
Yeah, it was just because I couldn't cover 100% with unit tests because I couldn't call some of the functions in the main package from another package. It might be just my problem, I don't know if this can be solved elegantly in Go, but I didnt find anything.

**Comment by Sergey1011010** [comment]
btw now the configuration is in different package conf

**Comment by Bee-lee** [comment]
@Sergey1011010 That is cool! So I guess take this task off me too:)

**Comment by Sergey1011010** [comment]
Closing since it's solved by one of previous PRs
