### ISSUE TITLE
Ability to display when the rule was added for all rules shown on OCM

### ISSUE THREAD

**Issue by tisnik** [RedHatInsights/insights-results-aggregator#133]
As an Insights user, I want to see when the rule was added (2 days ago etc.) for all rules displayed on OCM for my selected cluster so I will be able to see which issues are 'new' due to new checks implemented.

**Comment by bond95** [comment]
Column `Added` was added 
![image](https://user-images.githubusercontent.com/3332176/76316607-29fc9380-62db-11ea-91c4-b738d41d3237.png)

**Comment by bond95** [comment]
Done
