### ISSUE TITLE
Ability to display description and reason for all rule results on OCM

### ISSUE THREAD

**Issue by tisnik** [RedHatInsights/insights-results-aggregator#134]
As an Insights user, I want to see a description and reason for all rule results so I will be able to comprehend the meaning of issue, its impact on my cluster, and how to fix it.

**Comment by bond95** [comment]
Do you mean this description?
![image](https://user-images.githubusercontent.com/3332176/75555863-5c85d100-5a3d-11ea-9e18-5b233d9cc84c.png)

**Comment by Sergey1011010** [comment]
related PR https://gitlab.cee.redhat.com/biakymet/uhc-portal/merge_requests/3

**Comment by Sergey1011010** [comment]
closed by https://github.com/RedHatInsights/frontend-components/pull/394
