### ISSUE TITLE
Find out and test JavaScript libraries to transform Markdown sources into HTML

### ISSUE THREAD

**Issue by tisnik** [RedHatInsights/insights-results-aggregator#135]
# Description
Find out and test JavaScript libraries to transform Markdown sources into HTML

# Acceptance criteria
1. library needs to run in browser
1. it needs to be configurable, ie. "two stars" migth be transformed into `<b>`, `<strong>`, `<div class="strong">` etc.
1. hopefully it needs to be fast enough to be able to display descriptions and reasons for 50 rules under one second

# Goal
1. To use this library on our (mocked ATM) OCM

**Comment by bond95** [comment]
@tisnik with `ReactMarkdown` it's possible to customize output as you want: https://codepen.io/bond95/pen/XWbpvYb

**Comment by tisnik** [comment]
Cool @bond95 . Actually it seems we'll be able to reuse existing component on OCM. We need to have a talk about it tomorrow or day after.
