### ISSUE TITLE
Ability to filter issues on UI

### ISSUE THREAD

**Issue by tisnik** [RedHatInsights/insights-results-aggregator#151]
As an user I'd like to be able to filter issues according to several search criteria (description etc.) so I'll be able to narrow all results.

**Comment by bond95** [comment]
This issue is mostly for backend.

**Comment by tisnik** [comment]
Are we going to send the filter settings in real time to backend?

**Comment by tisnik** [comment]
I mean - it is possible, but I think that current component is able to do it on front end.

**Comment by bond95** [comment]
Ok, so we will do filtration on side of client, no problem.

**Comment by bond95** [comment]
Filtration is working on client side, but it should be implemented in RestAPI
![image](https://user-images.githubusercontent.com/3332176/76316425-e2760780-62da-11ea-916c-611f54dbf277.png)

**Comment by bond95** [comment]
Done
