### ISSUE TITLE
It might be good to log this situation as there migth be more causes

### ISSUE THREAD

**Issue by tisnik** [RedHatInsights/insights-results-aggregator#155]
https://github.com/RedHatInsights/insights-results-aggregator/blob/d337a3ac0833dc1da32dd9ff863178959515a551/migration/migration.go#L78

**Comment by natiiix** [comment]
Do you mean the info tab initialization error that caused the rollback? Because all the different errors can be logged from the `storage.Init` function. Maybe I should add more information to the SQL error messages for context.

**Comment by natiiix** [comment]
Thanks to various changes in the DB migration code, this issue has already been resolved some time ago.
