### ISSUE TITLE
Method for reading 'content' for insights rules periodically or on demand

### ISSUE THREAD

**Issue by tisnik** [RedHatInsights/insights-results-aggregator#156]
As a developer I need to be able to clone repository containing 'content' (templates for messages) for insights rules, so I'll be able to read content of this repository #157 and initialize in-memory cache to be served via REST API.

Reading (synchronizing) needs to be done periodically or on demand (via REST API probably, but only for selected users)

**Comment by Bee-lee** [comment]
Openshift rules content
https://gitlab.cee.redhat.com/insights-rules/insights-content/tree/master/content/shift

**Comment by JoseLSegura** [comment]
As far as we can see on the repository (I cherry picked some examples, so maybe I'm wrong), there is no templates at all. Every rule has its own "content" directory with a well defined layout of directories and files.
Some of the files are YAML and another ones are markdown files, but I cannot see any template on them, are just plain static markdown content for every rule

**Comment by tisnik** [comment]
That's correct, Ondra is going to create some description with real placeholders.

**Comment by JoseLSegura** [comment]
I want to see an example using placeholders, I cannot imagine one rule description that really needs placeholders, but I must recognize that I don't have very much imagination :-P
