### ISSUE TITLE
Processing 'content' for insights rules

### ISSUE THREAD

**Issue by tisnik** [RedHatInsights/insights-results-aggregator#157]
As developer I need to be able to process the whole repository with 'content' for insights rules so I'll be able to create in-memory representation of such data to be available via REST API.

Repository with 'content' (templates for messages) for insights rules has specified structure. We need to be able to go through cloned repository and create object from data that will be stored in memory (like a cache). In case of any error, the old version of the object will be used instead so the service won't be downgraded.

See also #156

**Comment by JoseLSegura** [comment]
Will it be more than one repository?
