### ISSUE TITLE
Make the 'content' for rules available via REST API

### ISSUE THREAD

**Issue by tisnik** [RedHatInsights/insights-results-aggregator#158]
As front end developer I need to be able to have 'content' for rules (messages markdown) available via REST API so I'll be able to process and show messages on web UI.

For the initial version: one rule per REST API call, but we might end with different solution (like mixing results with 'content' in one REST API call).

See also #156 and #157

**Comment by Bee-lee** [comment]
I will get together with @Sergey1011010 and @bond95 and gather what they need from the API etc.

Will update here.

**Comment by bond95** [comment]
Example of data that we should have on frontend
```JSON
 {
    "meta": {
      "count": 4,
      "page": 1,
      "perPage": 15
    },
    "data": [
      {
        "description": 'Some rule description',
        "created_at": 1583245000000,
        "total_risk": 3,
        "details": "..."
      },
      {
        "description": 'Some rule description2',
        "created_at": 1583245000000,
        "total_risk": 4,
        "details": "..."
      },
      {
        "description": 'Some rule description3',
        "created_at": 1583245000000,
        "total_risk": 1,
        "details": "..."
      },
    ],
  }
```

**Comment by Bee-lee** [comment]
`page` and `perPage` will be accepted as parameters, but will obviously have default values (10 per page).

Details will be the actual content of the rule.

Since pagination will be done on backend, filtering has to be done too - it will probably accept a dict of filters, depending if we will want to filter by multiple values. 
@natiiix This also means that we'll have to "understand" the rules on backend instead of not giving a hoot about the actual content

**Comment by Sergey1011010** [comment]
@bond95, we will also need some id for rules to be able to implement like & dislike feature

**Comment by tisnik** [comment]
Each rule has FQDN that can be used to that purpose. It needs changes in storage module though (which is ok)

**Comment by bond95** [comment]
@Bee-lee I forgot to mention about sort. We need to have sort in backend as well.

**Comment by bond95** [comment]
@Bee-lee I little bit updated response that we expect.

**Comment by Bee-lee** [comment]
@bond95 Ok, I see you added the ID now too, for the upvotes.

I have to find out how the `totalRisk` and `riskOfChange` is "calculated" from the `impact` and `likelihood` we have... :D

**Comment by tisnik** [comment]
@Bee-lee please ask Ondra or Baca

**Comment by Bee-lee** [comment]
@tisnik I wrote to Ondra when I posted the comment, I'm waiting response, but maybe someone can try to find out from the content-server? I tried a quick search across repos and not much, it might be another parameter in .yaml, but maybe not

https://gitlab.cee.redhat.com/insights-rules/insights-content/merge_requests/539/diffs

**Comment by Bee-lee** [comment]
Ondra said he will send it later, he's in a meeting atm

**Comment by Bee-lee** [comment]
Risk of change is *probably* (by Ondra's words "doufam...") another variable in error key's metadata.yaml called:
`resolution_risk: use the pre-defined resolution_risk in content/config.yaml file in insights-content repo (each resolution_risk relates to a risk level from 1 to 4, the higher the riskier the resolution is)` which we dont have.

FYI: Total risk = (int) ((likelihood + impact) / 2)

From the mockup, I checked which markdowns are used and it looks like it's only generic.md of error key https://gitlab.cee.redhat.com/search?utf8=%E2%9C%93&snippets=&scope=&repository_ref=master&search=fs.pipe-user-pages-soft&project_id=19008 which is currently empty for the one rule we have.
