### ISSUE TITLE
It might be better to add this check before sql.Open

### ISSUE THREAD

**Issue by tisnik** [RedHatInsights/insights-results-aggregator#165]
https://github.com/RedHatInsights/insights-results-aggregator/blob/ab5bb7c9770365641b6e8da7f4aabd715e5dcb1c/storage/storage.go#L110

Now the `default` branch can not be accessed by unit tests, that's one reason ;)

Another reason: the DB connection is keeping opened for unsupported driver

**Comment by Sergey1011010** [comment]
actually getDataSourceFromConfig already checks if driver is supported
