### ISSUE TITLE
Ability to disable a rule for selected cluster

### ISSUE THREAD

**Issue by tisnik** [RedHatInsights/insights-results-aggregator#169]
**Summary**
As an OCM user, I want to be able to disable a rule that I'm not interested in for a selected cluster, so that it won't be shown on the list of recommendations.

**Additional context**:
This story has gained a higher priority with the introduction of a Tutorial/Fake rule in Sprint 10, which is hit by all clusters in order to show something to the user. In the description of that rule it says that it's a testing rule and that the user has the ability to disable it.
The user can disable the rule by accident, or can later gain interest in a rule they disabled before, therefore the user also has to have an ability to easily see the disabled rules, as well as the ability to re-enable the rule that was disabled.
- A spike for the Design was created in JIRA (CCXDEV-1401)
- A task for backend part was created (#302)

**Unknowns**:

- design for `Disable rule`
- design for the user's ability to see disabled rules
- design for `Re-enable rule`

**Acceptance criteria**:

- the user can disable a rule from the list of recommendations
- the user can see the rules they've disabled
- the user can re-enable a disabled rule

**Comment by bond95** [comment]
@tisnik do we already have support of this feature on backend side?

**Comment by tisnik** [comment]
Unfortunately no ATM

**Comment by bond95** [comment]
Ok, so basically we can leave it on another sprint?

**Comment by Sergey1011010** [comment]
Done
