### ISSUE TITLE
OCM UI should support Firefox, Chrome(Chromium), and Safari

### ISSUE THREAD

**Issue by tisnik** [RedHatInsights/insights-results-aggregator#174]
As an user I want to be able to display OCM UI in Firefox, Chrome, Chromium, and Safari browsers so I will be able to use all mainstream systems and browsers.

**Comment by bond95** [comment]
It should support two latest major versions of Chrome, Firefox, Safari and Edge https://github.com/patternfly/patternfly#browser-support

**Comment by tisnik** [comment]
Cool, ty @bond95 . That Edge thing scare me a bit - how to test this crap?

**Comment by bond95** [comment]
Open Edge and test 😃

**Comment by bond95** [comment]
@tisnik https://www.microsoft.com/en-us/edge

**Comment by tisnik** [comment]
not supported on my work machine, but I can reserve Window box

**Comment by bond95** [comment]
As I see it's supported on Mac, so no problems

**Comment by bond95** [comment]
Safari Version 13.1 (14609.1.20.111.8):
![image](https://user-images.githubusercontent.com/3332176/78559564-de270680-7814-11ea-9f5f-63ba9fcecad3.png)
![image](https://user-images.githubusercontent.com/3332176/78561289-bf763f00-7817-11ea-9533-302445a41750.png)
![image](https://user-images.githubusercontent.com/3332176/78561694-77a3e780-7818-11ea-9587-046f05eba7b2.png)

Firefox Version 68.6.1esr (64-bit):
![image](https://user-images.githubusercontent.com/3332176/78559807-51c91380-7815-11ea-8fe8-9fa47aadc06c.png)
![image](https://user-images.githubusercontent.com/3332176/78561233-a8375180-7817-11ea-977c-01a0b8e9333e.png)
![image](https://user-images.githubusercontent.com/3332176/78561757-91452f00-7818-11ea-8cf9-08d4014c0d4a.png)

Edge Version 80.0.361.109 (Official build) (64-bit):
![image](https://user-images.githubusercontent.com/3332176/78560658-b46edf00-7816-11ea-8589-68e7085f0251.png)
![image](https://user-images.githubusercontent.com/3332176/78561185-92c22780-7817-11ea-82d6-48b5e628227d.png)
![image](https://user-images.githubusercontent.com/3332176/78561835-ade16700-7818-11ea-8f66-634c2a36868b.png)

Chrome Version 80.0.3987.132 (Official Build) (64-bit):
![image](https://user-images.githubusercontent.com/3332176/78560733-d0728080-7816-11ea-9115-a76e6a107af5.png)
![image](https://user-images.githubusercontent.com/3332176/78561364-e16fc180-7817-11ea-8c9f-56290187f557.png)
![image](https://user-images.githubusercontent.com/3332176/78561951-d9645180-7818-11ea-9681-f2a83f4e2f91.png)

No critical or important differences between functionality in different browsers were found.

**Comment by bond95** [comment]
@tisnik WDYT? ^

**Comment by tisnik** [comment]
LGTM, thank you so much

**Comment by quarckster** [comment]
From my perspective testing different browsers doesn't make much sense. In end-user application such as OCM UI and our Insights there shouldn't be any browser-specific code. Such kind of testing makes sense for underlying libraries such as react, patternfly-react and [insights-chrome](https://github.com/RedHatInsights/insights-chrome). In our UI tests we should check functionality and overall look and feel.
