### ISSUE TITLE
Benchmarks for consumer part

### ISSUE THREAD

**Issue by tisnik** [RedHatInsights/insights-results-aggregator#184]
As a developer I want to be able to run benchmarks that checks durability of consumer part of the aggregator application.

**Comment by Sergey1011010** [comment]
isn't it duplicate of https://github.com/RedHatInsights/insights-results-aggregator/issues/638?

**Comment by Sergey1011010** [comment]
Done by https://github.com/RedHatInsights/insights-results-aggregator/pull/640
