### ISSUE TITLE
Migrations don't work on postgres

### ISSUE THREAD

**Issue by quarckster** [RedHatInsights/insights-results-aggregator#188]
When I run `insights-results-aggregator` against an empty postgres db I can see this error:
```
2020/02/28 14:01:26 Initializing HTTP server at :8080
2020/02/28 14:01:26 pq: relation "migration_info" does not exist
```

**Comment by natiiix** [comment]
I have sort of anticipated this, but thankfully it's not terribly difficult to solve.

The error is here: https://github.com/RedHatInsights/insights-results-aggregator/blob/master/migration/migration.go#L78
