### ISSUE TITLE
Unable to parse results from ccx-data-pipeline

### ISSUE THREAD

**Issue by quarckster** [RedHatInsights/insights-results-aggregator#210]
I uploaded an insights archive and I got this message in the logs. Caught in CI environment.
```
2020/03/03 15:38:57 Error parsing message from Kafka: Improper report structure, missing key info
2020/03/03 15:38:57 Error processing message consumed from Kafka: Improper report structure, missing key info
```

**Comment by quarckster** [comment]
@tisnik  Here what I see in the logs now:
```
2020/03/03 16:47:24 Deserialied report read from message with improper structure:
```

**Comment by tisnik** [comment]
Hello @quarckster is it still an issue?

**Comment by quarckster** [comment]
No, it was fixed. ccx-data-pipeline was misconfigured in that line https://github.com/RedHatInsights/ccx-data-pipeline/blob/master/config.yaml#L5
