### ISSUE TITLE
Consider storing report as jsonb

### ISSUE THREAD

**Issue by Sergey1011010** [RedHatInsights/insights-results-aggregator#212]
Now we store report as a string, but it's a valid json and it would be better to use proper type which is more optimized in terms of storage and has rich support of indices.

**Comment by natiiix** [comment]
A quote from JIRA to clarify why this issue has been closed:

> We have decided that converting JSON columns in DB to a JSONB type is not a priority at the moment and that we wouldn't benefit from it in any significant way right now. If the situation changes and we start making complex SQL queries that require data from inside of the JSON cells, then we may consider using JSONB, but for the moment there are no such plans.
