### ISSUE TITLE
Create a push webhook in the ccx-rules-ocp repository pointing to our clusters

### ISSUE THREAD

**Issue by Bee-lee** [RedHatInsights/insights-results-aggregator#223]
To complete the functionality of #156 , we need to have a Push webhook in the ccx-rules-ocp repository to our openshift clusters in order to signalize that a rebuild is necessary.

The repository is: https://gitlab.cee.redhat.com/ccx/ccx-rules-ocp/

Since the support facing team is responsible for that repository, this task might require some communication with them.

**Comment by JoseLSegura** [comment]
I can write to them and ask if they agree to configure that webhook

**Comment by Bee-lee** [comment]
@quarckster created the webhook in https://gitlab.cee.redhat.com/ccx/ccx-rules-ocp and showed me how to do it. Thank you!

**Comment by JoseLSegura** [comment]
Only a question: I understand that the hook will be raised for every commit that is pushed to the master branch on that repository, but they can push commits that doesn't affect at all to the `content` directory, so probably there is no need to rebuild our container image or restart our service.

Maybe we can consider a functionality to check if there is new content in the commits before creating the new container image as a future improvement. WDYT?
