### ISSUE TITLE
Filtering by total risk works as expected

### ISSUE THREAD

**Issue by tisnik** [RedHatInsights/insights-results-aggregator#274]
# Filtering by total risk works as expected:

## Design:
https://marvelapp.com/852jaj9/screen/66423927 (click on the "moderate" button in the summary box to see how it works)

## Checks:
  * filter is added to the list of filters
  * "clear filters" link is added at the end of the filter list and it clears the filter when clicked
  * only rule results that have their total risk equal to what was selected are displayed
  * the same is applied to all levels of total risk (we iterate the test through all levels)

**Comment by Sergey1011010** [comment]
done by https://gitlab.cee.redhat.com/service/uhc-portal/merge_requests/1201
