### ISSUE TITLE
goconst doesn't fail the CI if errors were found

### ISSUE THREAD

**Issue by Sergey1011010** [RedHatInsights/insights-results-aggregator#324]
https://travis-ci.org/github/RedHatInsights/insights-results-aggregator/jobs/664002405?utm_medium=notification&utm_source=github_status

**Comment by JoseLSegura** [comment]
I was testing in local and apparently the goconst command doesn't return an status different to 0, so the `./goconst.sh` script cannot fail.
If we want to enforce this, probably we need to parse the `goconst` output by ourselves

**Comment by tisnik** [comment]
That's on purpose right now - all errors needs to be fixed first

**Comment by tisnik** [comment]
I've created my homework task: https://github.com/RedHatInsights/insights-results-aggregator/issues/339
