### ISSUE TITLE
Move repeated data for tests to `tests/testdata/`

### ISSUE THREAD

**Issue by Sergey1011010** [RedHatInsights/insights-results-aggregator#327]
So we can change it easily when format of report changes for example

**Comment by Sergey1011010** [comment]
`tests/testdata/` itself was moved to insights-results-aggregator-utils, so repeated data should be moved there as well

**Comment by joselsegura** [comment]
I was taking a look over the different `_test` packages and I didn't see any relevant data that can be moved to `testdata`.

Do you know about some data that I didn't realize?

**Comment by Sergey1011010** [comment]
@joselsegura After PR https://github.com/RedHatInsights/insights-results-aggregator/pull/904 is merged, I admit that we can close this issue
