### ISSUE TITLE
Users from different organizations can access to data under org id they don't belong

### ISSUE THREAD

**Issue by quarckster** [RedHatInsights/insights-results-aggregator#328]
Step to reproduce:
1. Upload two archives using two different accounts with different org id.
2. Fetch `/organization` using the credentials of these two users

Actual result:
Both users can see all organizations

Expected results:
Only the organization that the user belongs to should be shown

3. Fetch `/organizations/{org_id}/clusters` using the credentials of these two users

Actual result:
Both users can see all cluster even from under org id that they don't belong to

Expected results:
User should have access only to clusters under his org id

**Comment by tisnik** [comment]
Now it is possible to enforce auth. mode for server, but the check for orgID seems to be missing. It is a regression, so I'm reopening this bug.
