### ISSUE TITLE
Authentication enhancement

### ISSUE THREAD

**Issue by bond95** [RedHatInsights/insights-results-aggregator#362]
While I worked on https://github.com/RedHatInsights/insights-results-aggregator/issues/351 I find out that we don't any checks by orgId, so basically anyone who has valid JWT token can access to any data aggregator.
It was added in https://github.com/RedHatInsights/insights-results-aggregator/pull/94 , but it missed somehow.

**Comment by tisnik** [comment]
Is it different from https://github.com/RedHatInsights/insights-results-aggregator/issues/328 ?

**Comment by bond95** [comment]
Duplicate
