### ISSUE TITLE
Check whether user can leave feedback on this cluster

### ISSUE THREAD

**Issue by Sergey1011010** [RedHatInsights/insights-results-aggregator#399]
Current behaviour: Any authenticated user can leave feedback on any cluster
Expected behaviour: Only users from cluster's org_id can leave feedback

**Comment by Sergey1011010** [comment]
If I understand correctly, it should be closed by @bond95's PR https://github.com/RedHatInsights/insights-results-aggregator/pull/389

**Comment by bond95** [comment]
Yep
