### ISSUE TITLE
End-to-end tests for the whole pipeline + aggregator flow

### ISSUE THREAD

**Issue by tisnik** [RedHatInsights/insights-results-aggregator#41]
Acceptance criteria:

- Proper setup for all things (mocked Kafka, mocked storage/cache...)
- End-to-end test-like scenarios, for aggregator + pipeline

**Comment by Sergey1011010** [comment]
Is this one done since we have integration tests and all other mentioned stuff?

**Comment by tisnik** [comment]
It's been already implemented via IQE test framework.
