### ISSUE TITLE
Spike: investigate how to encrypt data in storage

### ISSUE THREAD

**Issue by tisnik** [RedHatInsights/insights-results-aggregator#42]
Spike: investigate how to encrypt data in storage

Acceptance criteria:
1. demo
1. benchmark results
1. comparison of benchmark results with no-encryption approach

It should not to be merged to master branch! We just need to know whether it is possible, because there's possibility we will be forced to use this approach.

**Comment by Sergey1011010** [comment]
Do we still want to investigate this bullshit? I don't see how it would make things even little bit safer and it's gonna take quite much time to implement.

**Comment by tisnik** [comment]
Nope, let's close it :)
