### ISSUE TITLE
New feature request: ability for customer to 'like' and 'dislike' the rule

### ISSUE THREAD

**Issue by tisnik** [RedHatInsights/insights-results-aggregator#43]
UX story on OCM:

As an user I want to be able to click on 'like' or 'dislike' icon for selected rule so I will be able to mark rules that are helpful or not.

Actions that would need to be implemented:

1) customer click on thumb-up or thumb-down if he/she likes or dislikes some rule (if it is helpful or not)
2) we will need to record this action
3) it might be shown somewhere, but not on OCM ATM

**Comment by Sergey1011010** [comment]
There are multiple questions that need to be discussed:

1 Do we need to allow every user to vote or only users with specific roles will be able to do that?
2 Do we need to store each user's vote or only the fact that somebody with access to this cluster voted?
3 Do we need to store and provide number of likes & dislikes? AFAIK we don't.
4 Do we need to show user his previous vote like on YouTube?
5 Will there be text feedback?
6 Will users be able to change their vote(text feedback)?
