### ISSUE TITLE
/clusters/{cluster_id}/rules/{rule_id} endpoints return 403 if auth is disabled

### ISSUE THREAD

**Issue by quarckster** [RedHatInsights/insights-results-aggregator#545]
If `INSIGHTS_RESULTS_AGGREGATOR__SERVER__AUTH` set to `False` /clusters/{cluster_id}/rules/{rule_id} endpoints on PUT method return 403.

Expected result:
PUT /clusters/{cluster_id}/rules/{rule_id}/(like|dislike|reset_vote) should return 200.

**Comment by Sergey1011010** [comment]
Why? If we don't have auth token there's nowhere to take user id from, so it can't return success

**Comment by quarckster** [comment]
I see, in that case `INSIGHTS_RESULTS_AGGREGATOR__SERVER__AUTH=False` doesn't make sense. It will never work.

**Comment by Sergey1011010** [comment]
@quarckster, well, some another endpoints still would work

**Comment by quarckster** [comment]
I don't think to have a flag that breaks some parts of the application not working makes sense. I see two solutions here:
* remove INSIGHTS_RESULTS_AGGREGATOR__SERVER__AUTH completely
* add `org_id` into the endpoints

**Comment by Sergey1011010** [comment]
@quarckster, actually not `org_id`, but `user_id` and it sounds weird to add it to the endpoint, we already have it in token.

**Comment by quarckster** [comment]
Actually, if you look at other endpoints we have redundant info as well:

* `/organizations/{org_id}/clusters`: `org_id` should be in the token
* `/report/{org_id}/{cluster_id}`: same here

**Comment by Sergey1011010** [comment]
@quarckster, I see the next solutions:

1. As @tisnik suggested, add test&debug get param user_id(used only when auth=false)
2. Keep the things as is, because adding another param to prod URL means adding more checks(not hard, but more points of failure)

What about other endpoints, good catch. I don't think it's a big deal, but we could remove redundant params at some point in the future.

**Comment by quarckster** [comment]
> add test&debug get param user_id(used only when auth=false)
I'm not sure how this will be described in openapi.json. Does it support conditions? And how will this work with the generated client?

So I would insist on removing `auth` option to preserve consistancy among all endpoints.
