### ISSUE TITLE
Ability to display simple analyses results in OCM

### ISSUE THREAD

**Issue by tisnik** [RedHatInsights/insights-results-aggregator#56]
As a subscriber to Red Hat products, I’d like to see simple analyses results about my clusters in OpenShift Cluster Manager portal

**Comment by bond95** [comment]
By simple analyses you mean this part of design?
![image](https://user-images.githubusercontent.com/3332176/75555945-89d27f00-5a3d-11ea-97e7-0785c23cff7a.png)

**Comment by tisnik** [comment]
Yes

**Comment by bond95** [comment]
Simple analyses results was added
![image](https://user-images.githubusercontent.com/3332176/76316314-ac388800-62da-11ea-897a-3e843a6d7846.png)

**Comment by bond95** [comment]
Done
