### ISSUE TITLE
Use "shortened" pagination on top and "full" pagination on bottom

### ISSUE THREAD

**Issue by tisnik** [RedHatInsights/insights-results-aggregator#561]
Use "shortened" pagination on top and "full" pagination on bottom

Preliminary design: https://marvelapp.com/852jaj9/screen/66458352

(I was told it is caused by broken CSS)

**Comment by bond95** [comment]
Will be fixed in https://gitlab.cee.redhat.com/service/uhc-portal/merge_requests/1229

**Comment by bond95** [comment]
done
