### ISSUE TITLE
Consistent display of insights rules analysis

### ISSUE THREAD

**Issue by tisnik** [RedHatInsights/insights-results-aggregator#57]
As a Insights user, I am presented with my Insights findings in a similar and consistent manner to my RHEL hosts so that I do not need to learn a new workflow that competes with other aspects of the same product

**Comment by bond95** [comment]
Maybe I missed something, but design that we have now is little different from that what we have in Insights, or you mean using same table component?

**Comment by tisnik** [comment]
From user perspective it should have the similar look & feel. Of course, the differences are (and must be) there, but we are asked to keep overall L&F the same.

**Comment by bond95** [comment]
Ok, so basically this task is about refactoring insights table, and using it?

**Comment by tisnik** [comment]
yes, from task point of view, yes

**Comment by bond95** [comment]
Ok, thank you.

**Comment by bond95** [comment]
Insights rules display is consistent with Insights Advisor 
![image](https://user-images.githubusercontent.com/3332176/76316192-74c9db80-62da-11ea-92f7-163f2f34d51e.png)

**Comment by bond95** [comment]
Done
