### ISSUE TITLE
Ability to display list of clusters

### ISSUE THREAD

**Issue by tisnik** [RedHatInsights/insights-results-aggregator#58]
As a Insights user, I am able to see a list of my OpenShift Clusters and drill in further on an individual cluster to view all issues identified for that cluster

**Comment by bond95** [comment]
But OCM UI already has cluster list, our task is basically add new tab to cluster detail view. Am I right?

**Comment by tisnik** [comment]
Yes, exactly.

**Comment by bond95** [comment]
So we can close it, because it's already done?

**Comment by tisnik** [comment]
The Insights tab is not there yet

**Comment by bond95** [comment]
So maybe will be better to rename issue, because name is little bit confusing. For example could be "Add Insights tab to cluster details in OCM"

**Comment by bond95** [comment]
Tab was added to OCM UI

**Comment by bond95** [comment]
Done
