### ISSUE TITLE
Logical grouping of rules

### ISSUE THREAD

**Issue by tisnik** [RedHatInsights/insights-results-aggregator#59]
As a Insights user, I am not able to see the number of all rules performed on my clusters, instead I’m able to see logical groups of rules defining large block/subsystems of rules

**Comment by bond95** [comment]
Could you, please, define by what criteria we will grouping rules?

**Comment by tisnik** [comment]
Currently the only grouping is by "Risk category". Icons with risks are displayed in top right, above the table.

**Comment by bond95** [comment]
So basically it's part of filters?

**Comment by tisnik** [comment]
user should be able to click on "Risk" icon and then the filter will be automatically created

**Comment by bond95** [comment]
Yep, I understand.

**Comment by bond95** [comment]
Grouping by total risk was added 
![image](https://user-images.githubusercontent.com/3332176/76316095-451ad380-62da-11ea-89d0-a9005d40d929.png)

**Comment by bond95** [comment]
Done
