### ISSUE TITLE
Summary for the 'fake' rule is not displayed on OCM UI

### ISSUE THREAD

**Issue by tisnik** [RedHatInsights/insights-results-aggregator#602]
![error_not_summary](https://user-images.githubusercontent.com/4579967/79972548-699bcb00-8496-11ea-8de6-e169ffae9bf9.png)

**Comment by bond95** [comment]
Attribute `details: ""` is empty, so problem somewhere in aggregator

**Comment by Bee-lee** [comment]
I'll tell support team to fill the `generic.md`. This was the question a couple days back if the details can fit a very long text. Guess we'll see

**Comment by tisnik** [comment]
ah so it is not summary.md? omg :)
