### ISSUE TITLE
RFE: It takes way too long to get results of first insights analysis

### ISSUE THREAD

**Issue by radekvokal** [RedHatInsights/insights-results-aggregator#608]
After insights archive is uploaded from a fresh installed clusters it takes way too long to see results of the analysis in OCM Insights tab. I have a cluster with 3 insights archives already uploaded (restarted and than upgraded insights operator) yet after 1hr 45mins still no insights results in OCM. The cluster is connected and monitoring data are available. Either we have to have a way how a new archive triggers analysis immediately or inform users that the first analysis will take some time before it pops up.

**Comment by Sergey1011010** [comment]
Closing because the issue was on insights operator controller side and was fixed by the following PRs:

https://github.com/openshift/insights-operator/pull/117
https://github.com/openshift/insights-operator/pull/118
