### ISSUE TITLE
Unit tests for all packages within this repository

### ISSUE THREAD

**Issue by tisnik** [RedHatInsights/insights-results-aggregator#62]
As a developer I'd expect that all packages within this repository are covered by unit tests so my refactorings and improvements will be checked accordingly.

**Comment by Sergey1011010** [comment]
aren't they covered now?

**Comment by JoseLSegura** [comment]
Update. After all the PRs about unit tests merged, are we ready for closing this parent task?

**Comment by Bee-lee** [comment]
Maybe increase coverage of consumer.go a bit (currently 76.8%) and then it should be good to go IMO.

**Comment by Sergey1011010** [comment]
@JoseLSegura I think we need to define the acceptance criteria for the task, for example "Each package has coverage >N%"

**Comment by JoseLSegura** [comment]
@Sergey1011010 agree. What about 85% overall, 80% per package? We are already very close to that number (the only one package behind 80% is `consumer` as @Bee-lee already said

**Comment by Sergey1011010** [comment]
@JoseLSegura, don't forget about main package

**Comment by Sergey1011010** [comment]
one task and we're done https://github.com/RedHatInsights/insights-results-aggregator/issues/423
