### ISSUE TITLE
Payload tracker integration

### ISSUE THREAD

**Issue by quarckster** [RedHatInsights/insights-results-aggregator#622]
In order to track a payload in the whole pipeline starting with ingress service, we should integrate with payload tracker service.

Ingress service return so-called request id. Having this request id you can track when your payload is handled by various services. At the moment the latest service where we can track insights operator archives is insights-storage-broker.

Here is the documentation https://github.com/RedHatInsights/payload-tracker#integration

Acceptance criteria:

 *  I should be able to see insights-results-aggregator in payload tracker when I enter request id returned by ingress service.

**Comment by Sergey1011010** [comment]
Is the link broken? I see 404

**Comment by quarckster** [comment]
it's a private repo please contact Richard Brantley @brantleyr for access granting.

**Comment by brantleyr** [comment]
@quarckster @Sergey1011010 I have added both of you. You should now be able to see the repo.
