### ISSUE TITLE
Workaround text is not separated from previous text

### ISSUE THREAD

**Issue by tisnik** [RedHatInsights/insights-results-aggregator#645]
![workaround](https://user-images.githubusercontent.com/4579967/80366844-41431080-888a-11ea-89a3-a50a13ac7c3a.png)

**Comment by bond95** [comment]
@tisnik it's look like issue was fixed, could you, please, check it?

**Comment by bond95** [comment]
@tisnik now text is separated, but line not wrapped. I think it's for another task, WDYT?
![image](https://user-images.githubusercontent.com/3332176/82674520-b9131980-9c43-11ea-9d9a-7996a7373be8.png)

**Comment by tisnik** [comment]
hmm wrapped command you said? It needs agreement with other people from design team :)
Other is perfectly ok, thank you
