### ISSUE TITLE
Fix for the problems with not stored offsets in Kafka broker

### ISSUE THREAD

**Issue by tisnik** [RedHatInsights/insights-results-aggregator#657]
### 1. Use some in memory storage which caches to disk(like Redis)

- Pros:
    - Fast as fuck

- Cons:
    - Extra deployment
    - Extra point of failure

### 2. Store in each record of report table

- Pros:
    - Ability to track last message offset for each report(do we need it?)
- Cons:
    - To be able to get the latest offset we would need an index which brings little overhead to insert

### 3. Store in another table as single row
- Pros:
    - No that much overhead as having index
- Cons:
    - Still not fast as fuck because we’re doing another query, but totally fine since we’re not doing “Big Data”

### 4. Make kafka library work by either figuring out why it throws weird errors or using another library. 
- Pros:
    - not much work probably
- Cons:
    - would be nice to know the offset, at least for debugging purposes

### 5. Keep everything as is and suffer
- Pros:
    - already done :)
- Cons: see description

**Comment by Sergey1011010** [comment]
> 4. Make kafka library work by either figuring out why it throws weird errors or using another library.
> 
>     Pros:
>         not much work probably

I don't think so, 2nd/3rd variant probably will take less time

**Comment by Sergey1011010** [comment]
Related issue https://github.com/RedHatInsights/insights-results-aggregator/issues/620
