### ISSUE TITLE
Broken spacing at Total risk status

### ISSUE THREAD

**Issue by doruskova** [RedHatInsights/insights-results-aggregator#659]
I noticed that something is wrong with the spacing/padding at Total risk status. It's jumping a little bit. 
And the gap between description and Total risk status in expanded row is small. It's 16px now, so please try 24px. @bond95 @Sergey1011010 
<img width="1361" alt="Snímek obrazovky 2020-04-28 v 14 38 36" src="https://user-images.githubusercontent.com/32618096/80488476-b08a3480-895e-11ea-8a9d-d2e909bd836f.png">

**Comment by bond95** [comment]
@doruskova as I see, since this issue a lot of things are changed and soon we will replace battery. So I think this task could be dropped. WDYT?
About gap, we use middle gap of patternfly which is equal to 1.5rem.

**Comment by bond95** [comment]
It was partially done before
