### ISSUE TITLE
Wrong link is used in popup window "What is Insights"

### ISSUE THREAD

**Issue by tisnik** [RedHatInsights/insights-results-aggregator#668]
It points to a dummy page about support. Probably it should link to https://docs.openshift.com/container-platform/4.3/support/remote_health_monitoring/about-remote-health-monitoring.html

**Comment by radekvokal** [comment]
This is the link we agreed on - https://docs.openshift.com/container-platform/latest/support/getting-support.html

**Comment by bond95** [comment]
Done
