### ISSUE TITLE
Design file format to store groups and tags for rules

### ISSUE THREAD

**Issue by tisnik** [RedHatInsights/insights-results-aggregator#700]
Design file format to store groups and tags for rules. It might be JSON, YAML, TOML, whatever.

## Acceptance criteria:
- description of the format to be part of our documentation
- ack across team

**Comment by natiiix** [comment]
An example of the designed file format can be found here: <https://github.com/RedHatInsights/insights-content-service/blob/master/groups_config.yaml>
