### ISSUE TITLE
Please update function name and its description. It is not a getter, the operation is like merge, merge-with

### ISSUE THREAD

**Issue by tisnik** [RedHatInsights/insights-results-aggregator#759]
https://github.com/RedHatInsights/insights-results-aggregator/blob/0c8cf3907c4336c5e7f0bf1094209089e4f8a617/server/server.go#L153

### Acceptance criteria
Function has a meaningful name that show what it does better than current name

**Comment by joselsegura** [comment]
Apparently this function doesn't exist anymore, probably refactored in some moment when the content parsing was removed. 

I will close it with no further action
