### ISSUE TITLE
Ability to retrieve recommendation text for the selected rule via REST API

### ISSUE THREAD

**Issue by tisnik** [RedHatInsights/insights-results-aggregator#772]
As a front end developer I'd like to be able to display new window/tab with rendered recommendation text for selected rule. In order to do it I need to be able to retrieve all relevant information via REST API.

An example (not real mock up):
https://cloud.redhat.com/insights/advisor/recommendations/ansible_deprecated_repo|ANSIBLE_DEPRECATED_REPO

**Comment by Sergey1011010** [comment]
So we want an endpoint for getting the list of all rules and another endpoint for getting the list of clusters accessible by current user where provided rule is hit, right?
