### ISSUE TITLE
Move rule content parsing code to insights-content-service

### ISSUE THREAD

**Issue by natiiix** [RedHatInsights/insights-results-aggregator#816]
## Description

In the future, the Aggregator will no longer serve the rule content. This functionality will be moved to the [Content Service](https://github.com/RedHatInsights/insights-content-service).

Therefore, it will make no sense to have the code for parsing rule content in the Aggregator anymore. Instead, the Content Service will serve the content, hence the name, so it also makes sense for it to contain the code for parsing rule content from disk.

## Acceptance criteria

- The `content` package is moved from Aggregator to Content Service, including all relevant tests.

**Comment by joselsegura** [comment]
This task should include the removal of the content package from the aggregator and remove the support for generating container images containing the rules.

Probably we need to change some repository trigger to avoid generating aggregator container images due to changes in rule contents
