### ISSUE TITLE
Disable Cloudwatch Log-Group creation by “insights-results-aggregator”

### ISSUE THREAD

**Issue by thearifismail** [RedHatInsights/insights-results-aggregator#835]
Disable Cloudwatch Log-Group creation by “insights-results-aggregator”?  The log group is now created by the `app-sre automation`, which blocks `ccs-data-pipeline` deployment when it tries to create the log group, which has already been created by app-sre.

For ccx-data-pipeline, written in Python, I did:
```
    handler = CloudWatchLogHandler(
        boto3_session=session,
        log_group=os.environ["CW_LOG_GROUP"],
        stream_name=os.environ["CW_STREAM_NAME"],
        create_log_group=False,
    )
```

**Comment by joselsegura** [comment]
As far as I can tell, the `cloudwatch` library used tries to create the group, but if it already exist (the creation returns an error), it use the existing one.

Probably @Sergey1011010 knows better about this

**Comment by thearifismail** [comment]
Rolling out `insights-results-aggregator` produced the following in the pod log:
```
aarif@MacBook-Pro~... $ oc logs -f insights-results-aggregator-4-zss7m
panic: AccessDeniedException: User: arn:aws:iam::351356922033:user/ccx-data-pipeline-stage is not authorized to perform: logs:CreateLogStream on resource: arn:aws:logs:us-east-1:351356922033:log-group:platform-dev:log-stream:insights-results-aggregator
	status code: 400, request id: dbf4cd63-0039-4cf3-834a-97db5cf2d108

goroutine 1 [running]:
main.main()
	/opt/app-root/src/aggregator.go:439 +0x1d7
aarif@MacBook-Pro~... $ 
```

**Comment by thearifismail** [comment]
What's the name of the Log-Group, it is supposed to create.  I am trying to deploy `ccx-data-pipeline`, which has s`insights-results-aggregator` and `insights-results-writer` both using the same docker image.

The log group under the engineering account is `CCX` but it has no log streams and under the appsre account the log-group is called `ccx-data-pipeline-stage`

**Comment by thearifismail** [comment]
Found the following in `config.toml` and `config-devel.toml`
```
log_group = "platform-dev"
stream_name = "insights-results-aggregator"
```

**Comment by thearifismail** [comment]
If what is said here is correct, then fixing  environment variables for the deployment config may fix the problem

**Comment by thearifismail** [comment]
If what is said [here](https://github.com/RedHatInsights/insights-results-aggregator/issues/835#issuecomment-636012194) is correct, then fixing environment variables for the deployment config may fix the problem

**Comment by Sergey1011010** [comment]
Hi. As @joselsegura said it tries to create a log group and if it exists, it will just use the group. But as I can see in the error, you're using the user that is not allowed to create groups(it handles this as an error). I'll add another option to use existing group.

**Comment by thearifismail** [comment]
@Sergey1011010 please let me when an image with your update is available.
