### ISSUE TITLE
Tooltip in a dashboard is too big

### ISSUE THREAD

**Issue by doruskova** [RedHatInsights/insights-results-aggregator#864]
<img width="937" alt="Snímek obrazovky 2020-06-11 v 10 59 08" src="https://user-images.githubusercontent.com/32618096/84366043-989b0700-abd2-11ea-9bec-24c0ac83bd07.png">

Is it possible to change the size/padding of a tooltip that appears when you hover on a bar chart? @bond95 

This is a preview from Insights: 
<img width="848" alt="Snímek obrazovky 2020-06-11 v 11 03 18" src="https://user-images.githubusercontent.com/32618096/84366508-35f63b00-abd3-11ea-8da0-60aa94e4d8a7.png">

**Comment by bond95** [comment]
@doruskova Yes, I'll take a look.

**Comment by bond95** [comment]
Done
