### ISSUE TITLE
Json response body  - unnecessary attributes/formatting

### ISSUE THREAD

**Issue by tremes** [RedHatInsights/insights-results-aggregator#874]
It's just a minor issue, but I am getting following response format for a rule content request:
```
{ "content": ..., "status": "ok" }
```
I don't see any value in wrapping the body in `content` attribute nor do I see any value in `status` attribute.

**Comment by bond95** [comment]
After discussion with @tremes we agreed that `status` field is needed, so it wouldn't be removed. Closing issue.

**Comment by tremes** [comment]
@bond95 Sorry I didn'ŧ fully agree... I only said I don't care much, that it depends on you :) and that the HTTP status code itself is sufficient for me :)

**Comment by bond95** [comment]
@tremes that's what I call agreed 😄
