### ISSUE TITLE
Story: Auth. scheme for accessing Insigts results from OCM

### ISSUE THREAD

**Issue by tisnik** [RedHatInsights/insights-results-aggregator#90]
As an user I expect I'll be able to be authorized and authenticated so I'll be sure that users from different organizations won't see results for clusters in my organization.

**Comment by bond95** [comment]
If I understand whole mechanism right, auth can be done through `x-rh-identity` which contains all needed information including `org_id` and `is_org_admin`

**Comment by tisnik** [comment]
It might be correct @bond95 , but we also need to check if the user is in the correct org id to get the data for given cluster.

**Comment by bond95** [comment]
@tisnik already done in https://github.com/RedHatInsights/insights-results-aggregator/pull/94

**Comment by tisnik** [comment]
I mean - let's say I'm user from organization X so I should not be able to see anything about clusters from organization Y.

**Comment by bond95** [comment]
> I mean - let's say I'm user from organization X so I should not be able to see anything about clusters from organization Y.

Yes, now it's working like this.

**Comment by tisnik** [comment]
Oh ok then. I must missed it in the PR.

**Comment by tisnik** [comment]
Is it possible pls. to have an example how it works for all three endpoints we have currently? TYVM!
