### ISSUE TITLE
GET /clusters/{clusterId}/report returns 404

### ISSUE THREAD

**Issue by quarckster** [RedHatInsights/insights-results-aggregator#907]
GET `/clusters/{clusterId}/report` returns 404 if it's performed by the user from different organization. Log excerpt:

```
{"level":"info","time":"2020-06-30T07:19:54Z","message":"Request received - URI: /api/insights-results-aggregator/v1/organizations/13275788/clusters/a8d80815-6112-4bde-9073-8c1c80acb432/users/6296823/report, Method: GET"}
{"level":"error","error":"Item with ID 13275788/a8d80815-6112-4bde-9073-8c1c80acb432 was not found in the storage","time":"2020-06-30T07:19:54Z","message":"Unable to read report for cluster"}
{"level":"error","error":"Item with ID 13275788/a8d80815-6112-4bde-9073-8c1c80acb432 was not found in the storage","time":"2020-06-30T07:19:54Z","message":"handleServerError"}
```

Steps to reproduce:

    1. Upload an archive using the credentials of one organization.
    2. Perform GET `/clusters/{clusterId from step 1}/report` with the credentials of another organization

Actual result:
Status code 404

Expected result:
Status code 403

**Comment by joselsegura** [comment]
We don't have right now a direct way to know which cluster names belong to each OrgID, so when we found no reports for this combination of OrgId and ClusterName, we are not able to distinguish the scenario where the cluster belongs to the organization, but we didn't receive a report yet and when this cluster doesn't belong to the organization.

**Comment by Sergey1011010** [comment]
@joselsegura we can change report endpoint so that it accepts only cluster ID(it's unique) and returns org ID which we can check on the proxy

**Comment by joselsegura** [comment]
@Sergey1011010 we are already checking the org ID in aggregator. Smart proxy doesn't have any information that will help to know if the absence of a report is because it was not received yet or it is because the cluster belongs to a different organization.

The only clue that we can take is to check that the ClusterID is already in the database for a different organization, and then we can deduce that this cluster doesn't belong to the current OrgID.

**Comment by Sergey1011010** [comment]
@joselsegura yes, as I said, we can add it to the report and check on smart proxy side.

**Comment by joselsegura** [comment]
@Sergey1011010 probably I'm missing something, but I don't see how checking the org id in smart-proxy would help.

**Comment by Sergey1011010** [comment]
@joselsegura we will return an error if org id doesn't match, it will be the same as returning error from the aggregator
