### ISSUE TITLE
Card with health checks by category is larger

### ISSUE THREAD

**Issue by doruskova** [RedHatInsights/insights-results-aggregator#927]
It looks that the card on the right is larger, but the font-size is still 14px. Something strange is happening here. Can you @bond95 take a look? 

<img width="1361" alt="Snímek obrazovky 2020-07-20 v 10 53 35" src="https://user-images.githubusercontent.com/32618096/87919281-dadc2180-ca77-11ea-885a-a9fa19b5b44f.png">

**Comment by bond95** [comment]
I'll take a look. Thank you.

**Comment by bond95** [comment]
Done
