### ISSUE TITLE
Create mechanism for DB migration 

### ISSUE THREAD

**Issue by bond95** [RedHatInsights/insights-results-aggregator#93]
Project now don't support DB migration, which makes a lot of problem on deploy. So we need to create mechanism for migrations that will check and update DB any time it's starting.

**Comment by natiiix** [comment]
Looking into <https://github.com/go-pg/migrations> to see if we could utilize it instead of having to write everything on our own.

**Comment by Sergey1011010** [comment]
@natiiix the problem is that this library is for postgres but we use sqlite as well
