### ISSUE TITLE
[Spike] ability to retrieve data for given cluster+rule from existing results table using JSON-query

### ISSUE THREAD

**Issue by tisnik** [RedHatInsights/insights-results-aggregator#959]
PSQL has the ability to use columns containing JSON data. The goal of this spike is to determine if it would be possible to use this technique to select reports for given `cluster_name`+`rule_name`. Right now the data are stored as raw string so probably new JSON index needs to be created.

**Comment by Sergey1011010** [comment]
I think it's better to change a goal to "determine if it's possible and effective", cuz if postgres doesn't have indices for arrays inside of a jsonb field, it's not a big optimization :)

**Comment by Sergey1011010** [comment]
Postgresql supports 2 types for handling JSON data: json and jsonb. The difference is that json is raw string without support for indices while jsonb is stored as binary and does support indices over JSON data. So, the solution would be:

1. Turn the report column to jsonb by a migration
2. Use the next query:

```
with cluster_data as (
    select * from report where cluster = 'b0c2d108-0603-41c3-9a8f-0a37eba5df49'
) 
select cluster_data.cluster, rule.*
from cluster_data, jsonb_to_recordset(cluster_data.report->'reports') as rule(component text, details jsonb, key text, links jsonb, rule_id text, tags jsonb, type text)
where component = 'ccx_rules_ocp.external.rules.cluster_wide_proxy_auth_check.report';
```

Which would return data in the next format:

```
 cluster_id |                             component                             |                                                                     details                                                                      |            key            | links |                 rule_id                 | tags | type 
------------+-------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------+-------+-----------------------------------------+------+------
          1 | ccx_rules_ocp.external.rules.cluster_wide_proxy_auth_check.report | {"type": "rule", "current": "4.3.0-0.ci-2020-01-06-150524", "desired": "4.3.0-0.ci-2020-01-11-070221", "error_key": "AUTH_OPERATOR_PROXY_ERROR"} | AUTH_OPERATOR_PROXY_ERROR | {}    | version_check|AUTH_OPERATOR_PROXY_ERROR | []   | rule
(1 row)

```

But, unfortunately, it's not possible to take an advantage of gin index for getting an object from a json aray(at least I haven't found a way), so, if we have a lot of rules, the query wouldn't be efficient.
