### ISSUE TITLE
Organizations endpoint should be plural

### ISSUE THREAD

**Issue by quarckster** [RedHatInsights/insights-results-aggregator#96]
Collections should be in plural from. https://github.com/RedHatInsights/insights-results-aggregator/blob/master/openapi.yml#L9 should be changed to `/organizations:`

**Comment by natiiix** [comment]
Yeah, I also thought it was strange. Presumably, the same thing applies to `/cluster` -> `/clusters`, right?

**Comment by quarckster** [comment]
@natiiix there is a guideline for that https://platform-docs.cloud.paas.psi.redhat.com/rest/urls.html#other-url-design-guidelines
